name: Deploy Second Repo to Subfolder

on:
  push:
    branches:
      - main  # Скрипт сработает автоматически, когда ты сделаешь push в ветку main

jobs:
  web-deploy:
    name: Deploying to Subfolder
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        
        # КРИТИЧЕСКИ ВАЖНАЯ СТРОКА:
        # Указываем путь к созданной подпапке. 
        # Если корень хостинга — это /public_html/, то для второго репозитория пишем:
        server-dir: /aurastoreproject.howto.rocks/htdocs/backend/
